default:
  cache_path: data/embeddings.pkl
  allowed_extensions:
    image:
      - .jpg
      - .jpeg
      - .png
    text:
      - .txt
      - .md
  search:
    top_k: 10
  db_path: data/
  server:
    host: 127.0.0.1
    port: 8081
  model:
    name: google/siglip2-so400m-patch16-naflex